# Application Properties
app:
  home-dir: /home/shubham-shinde/Temporary/CodingAppData

# Application Info
info:
  application:
    name: CodePlayground_
    description: CodePlayground an Online Coding Platform - Backend
    author: Shubham Shinde
    version: '@project.version@'

# Server Config
server:
  port: 8080

# Spring Security Config
logging:
  level:
    root: info
    org:
      springframework: info

# Database Config
spring:
  profiles:
    active: mariadb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
